# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sb_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 428)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 90, 171, 171))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.Label_Score1 = QtWidgets.QLabel(self.frame)
        self.Label_Score1.setGeometry(QtCore.QRect(0, 30, 171, 141))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Label_Score1.setFont(font)
        self.Label_Score1.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Score1.setObjectName("Label_Score1")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(210, 90, 171, 171))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.Label_Score2 = QtWidgets.QLabel(self.frame_2)
        self.Label_Score2.setGeometry(QtCore.QRect(0, 30, 171, 141))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Label_Score2.setFont(font)
        self.Label_Score2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Label_Score2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Score2.setObjectName("Label_Score2")
        self.Label_Team2 = QtWidgets.QLabel(self.frame_2)
        self.Label_Team2.setGeometry(QtCore.QRect(0, 0, 171, 41))
        self.Label_Team2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Team2.setObjectName("Label_Team2")
        self.Button_Connect = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Connect.setGeometry(QtCore.QRect(20, 270, 361, 41))
        self.Button_Connect.setObjectName("Button_Connect")
        self.Label_Team1 = QtWidgets.QLabel(self.centralwidget)
        self.Label_Team1.setGeometry(QtCore.QRect(20, 90, 171, 41))
        self.Label_Team1.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Team1.setObjectName("Label_Team1")
        self.Label_Time = QtWidgets.QLabel(self.centralwidget)
        self.Label_Time.setGeometry(QtCore.QRect(110, 10, 181, 71))
        font = QtGui.QFont()
        font.setFamily("FreeMono")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Label_Time.setFont(font)
        self.Label_Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Time.setObjectName("Label_Time")
        self.List_Log = QtWidgets.QListWidget(self.centralwidget)
        self.List_Log.setGeometry(QtCore.QRect(20, 320, 361, 81))
        self.List_Log.setObjectName("List_Log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Client-Scoreboard"))
        self.Label_Score1.setText(_translate("MainWindow", "0"))
        self.Label_Score2.setText(_translate("MainWindow", "0"))
        self.Label_Team2.setText(_translate("MainWindow", "Team1"))
        self.Button_Connect.setText(_translate("MainWindow", "Connect to current football match!"))
        self.Label_Team1.setText(_translate("MainWindow", "Team1"))
        self.Label_Time.setText(_translate("MainWindow", "00:00"))
